### PR TITLE
Add e-mails for SSC and EC

### PR DESCRIPTION
**Pull request by choldgraf**
In a recent round of communication with the SSC, I couldn't find the listserv e-mail for the group. This adds brief information for how to get in touch with the SSC and the EC so that others aren't confused like I was.

### CODE REVIEW

**Comment by Ruv7** [comment]
Hi Chris - I'm not familiar enough with GH to click about on this issue and figure out the exact spot where you're proposing to include this contact info but I would advise the thing to include would be a link pointing to the EC Team Compass which includes various ways to communicate with the EC including the EC email. https://executive-council-team-compass.readthedocs.io/en/latest/#contacting-the-executive-council

**Comment by jasongrout** [comment]
FYI, for the EC, we already have a section on the [team compass](https://jupyter.org/governance/executive_council.html#team-compass) and it specifically mentions how to contact the EC:

> The [Executive Council Team Compass](https://executive-council-team-compass.readthedocs.io/en/latest/) publishes information about the activities and operations of the EC, including how to contact the EC.

**Comment by jasongrout** [comment]
> I'd recommend putting a bit button at the top of that page like "for general information about the executive council go to the team compass" rather than nesting it in a subsection. Would that be acceptable for folks?

Yes, putting the team compass link at the very top sounds great! We already have a note at the top that points to the list of EC members. How about moving that team compass sentence (or something similar) up to the top as the very first sentence, even before the pointer to the list of people?

There's nothing like debugging existing docs by having people try to use them to solve problems. Thanks for coming back and making things better for the next person!

**Comment by choldgraf** [comment]
OK the latest push makes the EC docs a button. I didn't find any team compass information for the SSC so I left it as-is.

Here's what it looks like:

CleanShot 2024-05-20 at 15 48 12@2x


> There's nothing like debugging existing docs by having people try to use them to solve problems. Thanks for coming back and making things better for the next person!

This describes like 90% of my contributions to the Jupyter project 😅

**Comment by jasongrout** [comment]
Pinging @jupyter/software-steering-council for their approval

**Review by minrk — APPROVED** [review]

**Pull request merged**
