### PR TITLE
Explicitly include activities in the list of things not needing trademark approval in certain cases

### PR DESCRIPTION
**Pull request by jasongrout**
### Background or context to help others understand the change.

Recently we've had some inquiries in the trademarks committee about using Jupyter logos or the word "Jupyter" when advertising activities that used or taught Jupyter. 

### A brief summary of the change.

This helps resolve some confusion that came up recently about when it
was appropriate to use the word "Jupyter" and Jupyter logos when advertising activities
that used or taught Jupyter. It also reemphasizes that such use must
not imply sponsorship or endorsement.

### What is the reason for this change?

This further clarifies to the community appropriate uses of Jupyter trademarks.

**Alternatives to making this change and other considerations.**

## The process ❗

> The process for changing the governance pages is as follows:
> 
> * Open a pull request **in draft state**. This triggers a discussion and iteration phase
>   for your proposed changes.
> * When you believe enough discussion has happened,
>   **move the pull request to an active state**. This triggers a vote.
> * During the voting phase, no substantive changes may be made to the pull request.
> * The Steering Council will vote, and at the end of voting the pull request is merged or closed.
> 
> The discussion phase is meant to gather input and multiple perspectives from the community.
> Make sure that the community has had an opportunity to weigh in on
> the change **before calling a vote**. A good rule of thumb is to ask several steering council
> members if they believe that it is time for a vote, and to let at least one person review
> the pull request for structural quality and typos.

## Votes

> All votes are limited in time to 4 weeks after the voting phase begins. At the end of 4 weeks, the proposal passes if 2/3 of the votes are in favor (fractions of a vote rounded up to the nearest integer); otherwise the proposal is rejected and the PR is closed. Prior to the four-week limit, if at least 80% of the Steering Council has voted and 2/3 of the votes are in favor (fractions of a vote rounded up to the nearest integer), the proposal passes.

**The voting period for the PR is from 22 Aug 2022 to 19 Sep 2022 anywhere on earth 🌍**

@afshin
- [x] YES
- [ ] NO

@blink1073
- [x] YES
- [ ] NO

@Carreau
- [x] YES
- [ ] NO

@damianavila
- [x] YES
- [ ] NO

@ellisonbg
- [x] YES
- [ ] NO

@fperez
- [x] YES
- [ ] NO

@ivanov
- [x] YES
- [ ] NO

@jasongrout
- [x] YES
- [ ] NO

@jhamrick
- [ ] YES
- [ ] NO

@minrk
- [x] YES
- [ ] NO

@mpacer
- [ ] YES
- [ ] NO

@parente
- [ ] YES
- [ ] NO

@rgbkrk
- [ ] YES
- [ ] NO

@Ruv7
- [x] YES
- [ ] NO

@SylvainCorlay
- [x] YES
- [ ] NO

@takluyver
- [ ] YES
- [ ] NO

@willingc
- [ ] YES
- [ ] NO

### CODE REVIEW

**Review by minrk — APPROVED** [review]

**Comment by jasongrout** [comment]
@jupyter/steeringcouncil - I've opened this small change to the trademarks policy for voting. Voting ends 19 Sep 2022. This change helps clarify that *activities* that use Jupyter may also use Jupyter trademarks/logos without requiring approval. This helps answer queries we've received on the trademark committee, for example for training or educational activities that use Jupyter, etc.

**Review by Carreau — APPROVED** [review]

**Review by fperez — APPROVED** [review]
Looks good to me, many thanks for this clarification.

**Review by afshin — APPROVED** [review]

**Review by damianavila — APPROVED** [review]

**Review by minrk — APPROVED** [review]

**Comment by jasongrout** [comment]
A friendly ping to @ivanov, @jhamrick, @mpacer, @parente, @rgbkrk, @Ruv7, @SylvainCorlay, @takluyver, and @willingc to consider voting on this governance PR.

**Comment by jasongrout** [comment]
The voting period has closed, and it looks like we have 11 positive votes and no negative votes, so the PR is approved. Thanks everyone!

**Pull request merged**
