### PR TITLE
Add angus to ssc

### PR DESCRIPTION
**Pull request by choldgraf**
cc @Ruv7

### CODE REVIEW

**Review by rowanc1 — APPROVED** [review]

**Comment by Zsailer** [comment]
Thanks, @choldgraf! Congratulations, @agoose77. Excited to have your join the SSC and serve the community in this new role. I know you'll do great stuff! 

cc @jupyter/software-steering-council. Can someone from this group help onboard @agoose77 to the SSC?

**Comment by agoose77** [comment]
Thanks @Zsailer; I'm really looking forward to representing Jupyter Book and working with the wider Jupyter team!

**Comment by Zsailer** [comment]
Closing and re-opening this PR to trigger the Github Actions fix by in #237

**Comment by Zsailer** [comment]
All green! Merging!

**Comment by Zsailer** [comment]
@choldgraf or @agoose77, let's make sure to add you to the Jupyter website page too: https://jupyter.org/about#software-steering-council-members

Here is an example PR: https://github.com/jupyter/jupyter.github.io/pull/759

We need to eliminate having two sources of truth... but for now, this is the state of things 😅

**Pull request merged**
