### PR TITLE
Add Paul to steering council

### PR DESCRIPTION
**Pull request by Carreau**
We're still waiting for some votes but we have majority.

Once this is merged the merger is responsible to 

- [ ] add Paul on the steering council ml. 
- [ ] add him to the steering council team on GitHub.

### CODE REVIEW

**Comment by blink1073** [comment]
I am not an owner on either the mailing list or the steering council, so I can't check your boxes @Carreau.

**Comment by willingc** [comment]
Excellent!

**Comment by willingc** [comment]
Did we get an email re: this? I didn't see one. Either way. Huge +1 for Paul.

**Comment by blink1073** [comment]
You must have you emails collapsed to daily like I do, @willingc :smile:  The activity on the mailing list was this morning.

**Pull request merged**
