### PR TITLE
Remove political belief from JupyterDay CoC

### PR DESCRIPTION
**Pull request by rgbkrk**
Political Affiliation is something you do (and choose), it's not something you are. It is not the same as a protected class.

---

It also looks like github autocorrected line feeds when I made this edit from the UI.

### CODE REVIEW

**Comment by yuvipanda** [comment]
Ah, just saw the message about line endings. No big deal :)

**Comment by fperez** [comment]
Should this be closed? It seems to me that #56 is the same without the line-ending issue, right? If so, it seems we should close this and only work on #56, or am I missing something?

**Comment by rgbkrk** [comment]
There's more than one code of conduct in this repository, this one is for the JupyterDay CoC

**Comment by fperez** [comment]
Ah, sorry, I missed that fact, thanks! Will aprove then :)

**Comment by jasongrout** [comment]
I'm approving this change, not because of "choice" vs "identity", but because I think it's valuable to simplify the CoC. The list in question is a non-inclusive list, and we emphasize that we are "not limited" to only considering things in the list.

**Pull request merged**
