### PR TITLE
Clarify that images/videos of Jupyter applications can sometimes be used without permission

### PR DESCRIPTION
**Pull request by jasongrout**
## Questions to answer ❓

Please answer the following questions along with your proposed change:

**Background or context to help others understand the change.**

We've had several inquiries to the trademarks committee about using screenshots or videos of Jupyter applications. This helps clarify when approval is not necessary to use images or videos of Jupyter applications.

**A brief summary of the change.**

Add that you may use images or videos of Jupyter applications also where you may use logos or the word Jupyter without permission.

**What is the reason for this change?**

**Alternatives to making this change and other considerations.**

This is a simpler alternative to https://github.com/jupyter/governance/pull/85

## The process ❗

The process for changing the governance pages is as follows:

- [x] Open a pull request **in draft state**. This triggers a discussion and iteration phase
  for your proposed changes.
- [x]  When you believe enough discussion has happened,
  **move the pull request to an active state**. This triggers a vote.
- [x] During the voting phase, no substantive changes may be made to the pull request.
- [ ] The Steering Council will vote, and at the end of voting the pull request is merged or closed.

The discussion phase is meant to gather input and multiple perspectives from the community.
Make sure that the community has had an opportunity to weigh in on
the change **before calling a vote**. A good rule of thumb is to ask several steering council
members if they believe that it is time for a vote, and to let at least one person review
the pull request for structural quality and typos.

### CODE REVIEW

**Comment by meeseeksmachine** [comment]
This pull request has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/need-consent-to-include-jupyter-notebook-screenshots-in-manuscript/6900/3

**Review by minrk — APPROVED** [review]

**Review by damianavila — APPROVED** [review]

**Comment by jasongrout** [comment]
Two people already approved this, and I think relevant discussion already happened on #85. Moving to the voting phase.

**Review by ellisonbg — APPROVED** [review]

**Review by blink1073 — APPROVED** [review]

**Review by afshin — APPROVED** [review]

**Review by fperez — APPROVED** [review]
This seems simple and easy enough, thanks! I agree that some of the extra detail in #85 was probably unnecessary and I'm unsure of its legal standing (e.g. fair use questions around a simple screenshot) so I prefer the more basic language here.

Thanks!!

**Comment by jasongrout** [comment]
@jupyter/steeringcouncil - please vote. Thanks!

**Review by Carreau — APPROVED** [review]

**Comment by Carreau** [comment]
Approved.Thanks @jasongrout.

**Comment by mpacer** [comment]
Approved! Thanks @jasongrout

**Review by Ruv7 — APPROVED** [review]

**Comment by Ruv7** [comment]
Approved. Warm holiday greetings to everyone! Hope you're all healthy and safe.

**Review by willingc — APPROVED** [review]
Thanks @jasongrout

**Review by mpacer — APPROVED** [review]

**Review by takluyver — APPROVED** [review]

**Comment by Carreau** [comment]
We are at 11 approval (+1 Jason can't self-approve), we are thus above the 2/3 threshold of acceptance, and there is 2 weeks remaining on the voting period.

I've requested review from the remaining members; but I think we are above the threshold so it should be ok to merge soon.

**Comment by jasongrout** [comment]
That is an interesting case I hadn't thought of - if 2/3 of the entire steering council has already approved, then it automatically has a 2/3 majority no matter what happens, so it begs the question of why wait the 4 weeks. Also, 14 votes is 80% of 17 SC members, so if two more people vote, no matter what they vote, we hit the early merge criteria in the governance docs (80% participation, 2/3 approval from that 80%).

One idea of the 4 week time frame is that some people might still object, and IIRC in the past we've seen people change their votes when a discussion ensued after an objection. I'm happy to wait the 4 weeks on this one - I don't see an urgent need to merge. But it does bring up questions about when we might be able to merge early.

**Comment by Carreau** [comment]
Yes, that is why I said it "should be ok to merge early", I think some people will just get the ping now that their review has been requested, and for politeness I think it's a good thing to give them the opportunity to comment.

**Review by jhamrick — APPROVED** [review]

**Review by parente — APPROVED** [review]

**Comment by jasongrout** [comment]
We're up to the 80% quorum now, with 100% approval from those voting. This has now been open for voting for 6 days. It looks like the PR passes. Thanks everyone!

**Comment by rgbkrk** [comment]
✅  Approved these changes on behalf of jupyter/steeringcouncil after the fact.

😄  Thanks for going forward and not waiting the longer period.

**Pull request merged**
