### PR TITLE
Revert "Clarify social media posting guideline"

### PR DESCRIPTION
**Pull request by Ruv7**
Reverts jupyter/governance#239 - Charter changes need to. be reviewed by the EC.

### CODE REVIEW

**Comment by jasongrout** [comment]
Thanks. It does look like this PR was supposed to go under additional review before merging. We should have a mechanism for noting in PRs when additional approval is needed.

**Comment by ivanov** [comment]
Ana and Jason: when you don't reach out to provide feedback that something has gone against your rules, people will either likely do it again, or lose trust and bounce off when they find out they are being routed around.

I would have appreciated at @ mention here.

**Comment by jasongrout** [comment]
@ivanov, first, thanks for cleaning up a bunch of things around here. I noticed you were doing some general housekeeping that was long overdue over the past few days - much appreciated. And noted that mentioning you here would have been good - sorry.

With that particular PR, my understanding from discussion was that it was supposed to have had some more context and a call for review, but that info wasn't yet added to the PR to signal to everyone that it was opening a discussion and was a WIP at this point. We should also have reached out to @andrii-i here as well. @andrii-i, just to be clear, was your intention in https://github.com/jupyter/governance/pull/239 to open a discussion about that change?

**Comment by ivanov** [comment]
I assume @andrii-i was made aware since he opened #242

**Comment by andrii-i** [comment]
@jasongrout @ivanov Thank you both for looking into this, I have opened #242 as a draft with a sufficient description as the intention indeed was to open a discussion on the subject.

**Pull request merged**
