### PR TITLE
Add Jupyter Book to list of sub-projects

### PR DESCRIPTION
**Pull request by choldgraf**
### Background or context to help others understand the change.

Recently the [Jupyter Book](https://github.com/jupyter-book/team-compass) project has petitioned to become a Jupyter subproject. See https://github.com/jupyter/enhancement-proposals/issues/122 for an explanation and discussion, and https://github.com/jupyter/enhancement-proposals/pull/123 for the SSC vote. Since the SSC already voted, this PR is for the EC to vote.

### A brief summary of the change.

Adopt the [Jupyter Book project](https://github.com/jupyter-book/team-compass) as a Jupyter subproject. See [this document](https://docs.google.com/document/d/1AtM3FHcgIfac3G-4eu4eSzZamLjreUofZbNZ6FzpGgM/edit) for the comprehensive proposal and a list of repos that would be included in this new subproject.

## Voting

Vote is expected to close in TBD

### EC members/voting checkboxes

* @afshin
  * [x]  Yes
  * [ ]  No
  * [ ]  Abstain
* @ellisonbg
  * [x]  Yes
  * [ ]  No
  * [ ]  Abstain
* @jasongrout
  * [x]  Yes
  * [ ]  No
  * [ ]  Abstain
* @fperez
  * [x]  Yes
  * [ ]  No
  * [ ]  Abstain
* @Ruv7
  * [x]  Yes
  * [ ]  No
  * [ ]  Abstain
* @zsailer
  * [x]  Yes
  * [ ]  No
  * [ ]  Abstain

> ## The process ❗
> 
> The process for changing the governance pages is as follows:
> 
> * Open a pull request **in draft state**. This triggers a discussion and iteration phase
>   for your proposed changes.
> * When you believe enough discussion has happened,
>   **move the pull request to an active state**. This triggers a vote.
> * During the voting phase, no substantive changes may be made to the pull request.
> * The Executive Council and Software Steering Council will vote, and at the end of voting the pull request is merged or closed.
> 
> The discussion phase is meant to gather input and multiple perspectives from the community.
> Make sure that the community has had an opportunity to weigh in on
> the change **before calling a vote**. A good rule of thumb is to ask several Council
> members if they believe that it is time for a vote, and to let at least one person review
> the pull request for structural quality and typos.

### CODE REVIEW

**Comment by choldgraf** [comment]
cc @jupyter/executive-council and @jupyter/software-steering-council

**Comment by jasongrout** [comment]
@choldgraf - I took the liberty of adjusting your description to use the PR template, so it is consistent with other votes in this repo. Feel free to elaborate or expand on the info, or put a closing date on the vote. Since this has already had a discussion over in the JEP process and with the SSC, I went ahead and put a ballot here. If there are EC members that would like to have more discussion, of course feel free to post a comment here.

Chris, I think minimally a new subproject needs to have a council for making decisions. Do you have one already in place?

**Comment by choldgraf** [comment]
Hey Jason - thanks for that, I appreciate it!

And yes the council will be the same people to begin (they will be two distinct councils and have the same membership for now, but will likely diverge in the future)

**Comment by ellisonbg** [comment]
@choldgraf can you clarify more of what you mean by "two distinct councils"? The governance model requires subprojects to have a single council to ensure that there is clear ownership and decision making for the subproject. Councils can use whatever internal structure they want to manage the project, but there should still be a single body that is ultimately responsible for making decisions. For example, the frontends subproject has many different repos and different subsets of people informally tend to work on and make decision and the different repos in the orgs. When major cross-cutting decisions come up though, it is the entire and single council that makes the decision. The EC is more than willing to meet and talk through more of how this would work for Jupyter Book. Excited to see this moving forward :-)

**Comment by rowanc1** [comment]
Hi @ellisonbg  -- there is only one Steering Council in Jupyter for JupyterBook. @choldgraf was referring to the fact that some portions of the project we are not bringing with us (e.g. there are hundreds of repositories that we created in that project, and not all of them are appropriate to be stewarded by Jupyter). There is more information in the proposal here:
https://github.com/jupyter/enhancement-proposals/pull/123#pullrequestreview-2145856036
I hope that helps!

**Comment by ellisonbg** [comment]
Ahh, thanks for the context that makes complete sense.

**Comment by fperez** [comment]
Just for the record - I voted in the affirmative quickly b/c I've been working closely with the team for a long time, but obviously we want to make sure any remaining questions are answered. Thanks @ellisonbg for checking in with those questions and @jasongrout for comments too!

I'm personally excited to see this moving forward, thanks all for the years of hard work leading to this!

**Comment by jasongrout** [comment]
It looks like the vote is already unanimously positive here for the EC, and is unanimously positive for the SSC over at https://github.com/jupyter/enhancement-proposals/pull/123. As such, I think this vote passes and we can merge. Thanks everyone, and welcome Jupyter Book as a subproject!

**Comment by jasongrout** [comment]
As a process matter, I will invite jupyter-book to join the Jupyter Enterprise org.

**Comment by jasongrout** [comment]
Also, can you send me the google group address for the Jupyter Book Council email list?

**Comment by fperez** [comment]
Woot, thanks everyone! 🎉 

Special thanks to @rowanc1 @choldgraf for a huge amount of sustained work over the years to bring us here. I'm excited about the good that will come out of this now being 💯 part of Jupyter!

**Pull request merged**
