### PR TITLE
Update Community Building Committee members

### PR DESCRIPTION
**Pull request by jasongrout**
### Background or context to help others understand the change.

We recently had some changes in the Community Building Committee. This PR updates the list of members.

I'm not sure that this needs a full steering council vote, but it would be good for @marthacryan and @rcthomas to approve in comments, publicly declaring their willingness to serve.

As part of this change, @SylvainCorlay stepped down to concentrate on running JupyterCon as the JupyterCon chair. We are so thankful for his service on the committee, and look forward to working with him on JupyterCon and other community activities.

### Alternatives to making this change and other considerations.

> ## The process ❗
> 
> The process for changing the governance pages is as follows:
> 
> * Open a pull request **in draft state**. This triggers a discussion and iteration phase
>   for your proposed changes.
> * When you believe enough discussion has happened,
>   **move the pull request to an active state**. This triggers a vote.
> * During the voting phase, no substantive changes may be made to the pull request.
> * The Steering Council will vote, and at the end of voting the pull request is merged or closed.
> 
> The discussion phase is meant to gather input and multiple perspectives from the community.
> Make sure that the community has had an opportunity to weigh in on
> the change **before calling a vote**. A good rule of thumb is to ask several Steering Council
> members if they believe that it is time for a vote, and to let at least one person review
> the pull request for structural quality and typos.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Thanks, this looks good to me.

**Comment by rcthomas** [comment]
LGTM here, thanks!

**Comment by marthacryan** [comment]
Looks good, thanks!

**Comment by jasongrout** [comment]
Welcome again, Martha and Rollin, and thanks again, Sylvain!

**Pull request merged**
