### PR TITLE
Process for creation of new repos in incubator projects.

### PR DESCRIPTION
**Pull request by fperez**
As per discussion on the mailing list.

### CODE REVIEW

**Comment by rgbkrk** [comment]
:+1:

**Comment by damianavila** [comment]
:+1:

**Comment by ellisonbg** [comment]
+1

On Sun, Nov 22, 2015 at 5:17 PM, Damián Avila <notifications@github.com>
wrote:

> [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/governance/pull/10#issuecomment-158825070>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
:+1:

**Comment by minrk** [comment]
:+1:

**Comment by minrk** [comment]
[link to list discussion](https://groups.google.com/forum/#!topic/jupyter/F5JtivSQunU) for reference.

**Comment by fperez** [comment]
Thanks everyone!

**Comment by jasongrout** [comment]
A belated +1

**Pull request merged**
