### PR TITLE
Ana replacing Brian of NumFOCUS subcommittee

### PR DESCRIPTION
**Pull request by ivanov**
per https://groups.google.com/forum/#!msg/jupyter-steering/53KsKBreBpM/ane3nB5MAgAJ
(thread only viewable by steering council)

@jupyter/steeringcouncil

### CODE REVIEW

**Comment by jasongrout** [comment]
Additionally, Fernando and Min +1'd the thread.

**Comment by jasongrout** [comment]
I'm with Ana and she said she's in favor as well, that puts us at 10 for, none against, which is 59%. How about we call the vote on Wednesday 11 Sep. If no major objections have been voiced by that point, we merge?

**Comment by ivanov** [comment]
with 14 voters, all in favor, we're moving forward with this.

**Comment by ivanov** [comment]
congratulations @Ruv7 !

**Pull request merged**
