### PR TITLE
Jupyter Community Building Committee Proposal

### PR DESCRIPTION
**Pull request by Ruv7**
## Votes
@afshin 
 - [x] YES
 - [ ] NO

@blink1073
 - [x] YES
 - [ ] NO

@Carreau
 - [x] YES
 - [ ] NO

@damianavila
 - [x] YES
 - [ ] NO

@ellisonbg
 - [x] YES
 - [ ] NO

@fperez
 - [x] YES
 - [ ] NO

@ivanov
 - [ ] YES
 - [ ] NO

@jasongrout
 - [x] YES
 - [ ] NO

@jhamrick
 - [ ] YES
 - [ ] NO

@minrk
 - [x] YES
 - [ ] NO

@mpacer
 - [x] YES
 - [ ] NO

@parente
 - [x] YES
 - [ ] NO

@rgbkrk
 - [ ] YES
 - [ ] NO

@Ruv7
 - [x] YES
 - [ ] NO

@SylvainCorlay
 - [x] YES
 - [ ] NO

@takluyver
 - [ ] YES
 - [ ] NO

@willingc
 - [x] YES
 - [ ] NO

## Questions to answer ❓

Please answer the following questions along with your proposed change:

**Background or context to help others understand the change.**
To make best use of our resources and encourage the growth of the Jupyter community we are proposing a new committee to lead and manage these efforts.

## The process ❗

The process for changing the governance pages is as follows:

* Open a pull request **in draft state**. This triggers a discussion and iteration phase
  for your proposed changes.
* When you believe enough discussion has happened,
  **move the pull request to an active state**. This triggers a vote.
* During the voting phase, no substantive changes may be made to the pull request.
* The Steering Council will vote, and at the end of voting the pull request is merged or closed.

The discussion phase is meant to gather input and multiple perspectives from the community.
Make sure that the community has had an opportunity to weigh in on
the change **before calling a vote**. A good rule of thumb is to ask several steering council
members if they believe that it is time for a vote, and to let at least one person review
the pull request for structural quality and typos.

### CODE REVIEW

**Comment by Ruv7** [comment]
Hello everyone! We welcome feedback, comments, questions on this proposal and will leave this in draft state until Friday July 30th.

**Comment by Ruv7** [comment]
Moving this into the voting phase slightly early as there hasn't been any discuss or feedback to date. This doesn't mean we're not open to feedback, questions or concerns. Don't hesitate to give your thoughts but also please go ahead and vote when you're ready.

**Review by Carreau — APPROVED** [review]

**Comment by fperez** [comment]
Thank you so much @Ruv7, @jasongrout and others for getting this part of the project properly structured. I've voted already, but wanted to publicly flag how grateful I am for your diligence here...

**Review by damianavila — APPROVED** [review]

**Review by SylvainCorlay — APPROVED** [review]

**Review by minrk — APPROVED** [review]

**Comment by blink1073** [comment]
Note: voting will close in six more days (26 August) or if we get one more vote, which would put us above the 80% threshold.

**Comment by jasongrout** [comment]
> or if we get one more vote

(to be clear, if there is one more *positive* vote...)

**Pull request merged**
