### PR TITLE
Update tier 1 institutional partners

### PR DESCRIPTION
**Pull request by blink1073**
Updated based on known affiliations.

cc @damianavila @willingc @ellisonbg @Carreau who I also updated, for approval.

### CODE REVIEW

**Comment by ellisonbg** [comment]
+1

**Comment by SylvainCorlay** [comment]
+1
btw I see Quansight listed in the sponsor section as well. Was there a donation from Quansight to Jupyter?

**Comment by willingc** [comment]
+1

**Comment by blink1073** [comment]
Thanks all!

**Pull request merged**
