### PR TITLE
Adds election tabulation script

### PR DESCRIPTION
**Pull request by jweill-aws**
### Background or context to help others understand the change.

This script converts the CSV produced by the Google Form for Jupyter Executive Council elections into a format compatible with the [Apache STeVe](https://github.com/apache/steve) tabulation script.

### A brief summary of the change.

The script produces a list of candidates and a summary of ranked-choice votes for tabulation with the Single Transferable Vote (STV) mechanism implemented in Apache STeVe.

### What is the reason for this change?

This is to tabulate the results from Jupyter Executive Council elections.

### Alternatives to making this change and other considerations.

Apache STeVe has a server component that we could use to run elections; we have not yet used this.

> ## The process ❗
> 
> The process for changing the governance pages is as follows:
> 
> * Open a pull request **in draft state**. This triggers a discussion and iteration phase
>   for your proposed changes.
> * When you believe enough discussion has happened,
>   **move the pull request to an active state**. This triggers a vote.
> * During the voting phase, no substantive changes may be made to the pull request.
> * The Steering Council will vote, and at the end of voting the pull request is merged or closed.
> 
> The discussion phase is meant to gather input and multiple perspectives from the community.
> Make sure that the community has had an opportunity to weigh in on
> the change **before calling a vote**. A good rule of thumb is to ask several Steering Council
> members if they believe that it is time for a vote, and to let at least one person review
> the pull request for structural quality and typos.

### CODE REVIEW

**Comment by jasongrout** [comment]
Thanks!

Could you add example input and output files? I'd love to have an automated test, but at least having example inputs and outputs will help us manually test changes.

Also, this repo is licensed CC0 (https://github.com/jupyter/governance/blob/main/intro.md#license-of-governance-documents) - however, maybe it's not clear what the license on the code here is (since the repo license refers to governance documents). Could you add a license statement at the top of the code file to be clear?

**Comment by jweill-aws** [comment]
@jasongrout Updated the README with more details on input and sample outputs, and added a CSV file as a sample input.

**Comment by jweill-aws** [comment]
I have used this script to do data prep for Jupyter Executive Council election tabulation last week.

**Comment by jasongrout** [comment]
I ran some tests also with these instructions, and the instructions and scripts and examples seem to work great. Thanks Jason!

**Pull request merged**
