### PR TITLE
Software Steering Council

### PR DESCRIPTION
**Pull request by afshin**
## The Software Steering Council

The scope of this PR is to describe the Software Steering Council, one of the main, high-level governance structures proposed for the new model as described in the [JupyterCon 2020 presentation](https://docs.google.com/presentation/d/12My88DsSIWnxZErDs6NT_nDqCVDNjwGDzsEDhQF2ho4/edit#slide=id.ga1b16488ee_1_0). 

We feel that the Software Steering Council is useful and complete enough to move forward with now, so we are moving this to the voting phase. Please comment below if you have further items to discuss about the Software Steering Council.

For the time being, the existing Jupyter Steering Council will function as the "Executive Board" mentioned in this document. We are working toward another PR for the Executive Board to replace the Jupyter Steering Council.

---

This vote closes on November 12 (anywhere on Earth) or earlier if 14 or more members of the Steering Council have voted.

> All votes are limited in time to 4 weeks after the voting phase begins. At the end of 4 weeks, the proposal passes if 2/3 of the votes are in favor (fractions of a vote rounded up to the nearest integer); otherwise the proposal is rejected and the PR is closed. Prior to the four-week limit, if at least 80% of the Steering Council has voted and 2/3 of the votes are in favor (fractions of a vote rounded up to the nearest integer), the proposal passes.

(cf. [governance.md](https://github.com/jupyter/governance/blob/master/governance.md#changing-the-governance-documents))

---

## Votes

@afshin
- [x] YES
- [ ] NO

@blink1073
- [x] YES
- [ ] NO

@Carreau
- [x] YES
- [ ] NO

@damianavila
- [x] YES
- [ ] NO

@ellisonbg
- [x] YES
- [ ] NO

@fperez
- [x] YES
- [ ] NO

@ivanov
- [x] YES
- [ ] NO

@jasongrout
- [x] YES
- [ ] NO

@jhamrick
- [ ] YES
- [ ] NO

@minrk
- [x] YES
- [ ] NO

@mpacer
- [x] YES
- [ ] NO

@parente
- [x] YES
- [ ] NO

@rgbkrk
- [x] YES
- [ ] NO

@Ruv7
- [x] YES
- [ ] NO

@SylvainCorlay
- [x] YES
- [ ] NO

@takluyver
- [x] YES
- [ ] NO

@willingc
- [x] YES
- [ ] NO

### CODE REVIEW

**Comment by meeseeksmachine** [comment]
This pull request has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/governance-office-hours-meeting-minutes/1480/143

**Comment by meeseeksmachine** [comment]
This pull request has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/governance-office-hours-meeting-minutes/1480/147

**Comment by jasongrout** [comment]
I just noticed that this PR does not add this new document to the table of contents, so it does not show up in the officially rendered governance website: https://jupyter.org/governance

Was that intentional? Are we planning on "revealing" this to the community in the governance webpage in concert with the other governing body?

**Comment by afshin** [comment]
> I just noticed that this PR does not add this new document to the table of contents, so it does not show up in the officially rendered governance website: https://jupyter.org/governance
> 
> Was that intentional? Are we planning on "revealing" this to the community in the governance webpage in concert with the other governing body?

I overlooked this when I opened it and I don't think it was the intention of any of the other authors of the text.

**Comment by jasongrout** [comment]
> I overlooked this when I opened it and I don't think it was the intention of any of the other authors of the text.

I made a PR to add it to the table of contents: https://github.com/jupyter/governance/pull/119

**Pull request merged**
