### PR TITLE
Move the circleci CI to a GitHub action

### PR DESCRIPTION
**Pull request by jasongrout**
This is an infrastructure change, moving our existing CircleCI action which builds a copy of the docs for a PR over to GitHub actions.

### CODE REVIEW

**Comment by jasongrout** [comment]
I think this is ready for review. When this is merged, I can delete the CircleCI integration in this repo.

**Review by choldgraf — APPROVED** [review]
LGTM! In the future we might also consider using ReadTheDocs for this, so that we can get a nice preview of docs changes (though then we'd need to host at `governance.jupyter.org` instead of `jupyter.org/governance`)

**Comment by jasongrout** [comment]
> so that we can get a nice preview of docs changes

To be clear, currently someone can download the artifact from the action and preview the docs changes. But yes, it's a lot simpler to just to a URL to see the preview.

**Review by minrk — APPROVED** [review]

**Comment by jasongrout** [comment]
Thanks Min! Since this is an infrastructure change, I think any steering council member should feel free to merge if you think it looks good to you ( if  you agree, of course).

**Pull request merged**
