### PR TITLE
CC0 license

### PR DESCRIPTION
**Pull request by jasongrout**
As mentioned in #8 by @njsmith, it would be great to license the governance documents as CC0.

We'll need explicit assent from me, @ellisonbg, @Carreau, and @minrk.  The one other author in the repo just fixed a link.  @fperez, it probably wouldn't hurt to have your assent too, since you likely had lots of input, even if you aren't credited in the repo.  Are there any others we need to get permission from?

*Edit: CC0 is basically public domain, but explicitly waives rights for jurisdictions that don't have the concept of public domain.  Basically, it tries to be as public domain as possible in all jurisdictions.  See https://creativecommons.org/publicdomain/zero/1.0/*

 - [x] Matthias
 - [x] Brian
 - [x] Fernando
 - [x] Jason
 - [x] Jess
 - [x] Damian
 - [x] Jon
 - [x] Min
 - [x] Kyle
 - [ ] Thomas

### CODE REVIEW

**Comment by jasongrout** [comment]
+1 for this PR, and I give my consent for a CC0 license.

**Comment by Carreau** [comment]
I'm ok on relicensing to CC0.

**Comment by jasongrout** [comment]
It seems that there is a general consensus.  @jupyter/steeringcouncil: Please vote on merging this PR. We need at least 8 votes, and 2/3 majority for merging.

**Comment by jdfreder** [comment]
Had to read about CC0 because I had never heard about it, but now I'm +1

**Comment by jasongrout** [comment]
@jdfreder, I added a note about what CC0 is in the pr description above.

**Comment by ellisonbg** [comment]
+1

On Thu, Oct 8, 2015 at 12:14 PM, Jonathan Frederic <notifications@github.com
> wrote:

> Had to read about CC0 because I had never heard about it, but now I'm +1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/governance/pull/9#issuecomment-146597525>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jhamrick** [comment]
:+1:

**Comment by Carreau** [comment]
Updated with checkbox list, to get a quick count.

**Comment by rgbkrk** [comment]
:+1: CC0

**Comment by damianavila** [comment]
:+1:

**Comment by fperez** [comment]
Yes, I'm not credited in but I did have a lot of input :)

I'm +1 on CC-0 on these, I hope they get spread as far and wide as possible!

**Comment by minrk** [comment]
:+1:

**Pull request merged**
