### PR TITLE
Add Code of Conduct documents

### PR DESCRIPTION
**Pull request by Ruv7**
Moving the Code of Conduct conversation/editing from Google Docs to this repo

### CODE REVIEW

**Comment by rgbkrk** [comment]
Turned off the CI since this code base doesn't need it.

**Comment by rgbkrk** [comment]
Thanks for helping put this together all!

**Comment by minrk** [comment]
Thanks for taking the lead on this!

**Comment by Carreau** [comment]
I disabled Travis.

**Comment by willingc** [comment]
@Carreau Thanks for disabling Travis :sunflower:

**Comment by Carreau** [comment]
Thanks all, this has been unactive for some time I'm going to merge and we can iterate on subsequent PRs.

**Comment by rgbkrk** [comment]
:+1: thanks Matthias

**Comment by fperez** [comment]
Great, thanks!

**Comment by willingc** [comment]
Thanks :cake:

**Pull request merged**
